XX1/VLS128 compatibility
tier4/LiDARTag pull request #11
Opened 2022-05-11 05:31 UTC by knzo25

## PR Type

- Improvement

## Related Links

 - [Ticket](https://tier4.atlassian.net/browse/T4PB-17307)

## Description

Added a profile for the velodyne vls128 lidar
Parameterized the maximum ring difference criteria to add points to a cluster (usually should not be needed but one of our lidars was missing a channel so this acts as a hotfix)
Fixed the reflection problem due to the naive use of the SVD method to estimate rotations

*Note: the decoding fails terribly so I just lowered the required score until we have an alternative

## Review Procedure

Using the data from Kashiwa (04/28) evaluate that the lidartag works as expected in cameras 0, 1, and 2.
Evaluate that disabling the SVD sign fix detections are omitted and that using the fix does not cause any problems.
Validate that using the previous thresholds for decoding causes most tags to be missed.

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]
- [ ] (When added something to `.repos`) Check if proper access rights are set

## CI Checks

- **vcs import**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2022-05-11 05:31 UTC, knzo25 commented
@sgk-000 
PRの数が増えないようにお願いいたします

2022-05-16 06:14 UTC, yabuta requested changes

2022-05-16 06:14 UTC, yabuta commented on include/lidartag/lidartag.hpp
> +    int np_ring; // Unused
使われていなければ削除してしまっても良さそうですがどうでしょう？

2022-05-16 06:14 UTC, yabuta commented on launch/lidartag_master.launch.xml
> +      <param name="min_rkhs_score" value="3.0" /> <!--default is 12.0 -->
このコメントのdefault is 12.0も3.0に変えてしまっても良さそうかと思いますがどうでしょう？

2022-05-16 06:14 UTC, yabuta commented on launch/lidartag_velodyne_vls128.launch.xml
> +    <arg name="linkage_ring_max_dist" value="2" /> <!-- This parameter be 1, but our lidar is missing one channel and this work as a hotfix -->
暫定処置の場合はコメントにTODOを書いてもらってもいいでしょうか？
これがTODOならコメントの先頭にTODOって追加してください

2022-05-16 06:14 UTC, yabuta commented on src/utils.cpp
> +  /** Eigen Version -> Replaced by OpenCV since sgk-000 reported numerical unstability (unconfirmed)
ここもテスト用コードなら消してしまって良さそうです

2022-05-16 07:41 UTC, knzo25 commented on launch/lidartag_master.launch.xml
> +      <param name="min_rkhs_score" value="3.0" /> <!--default is 12.0 -->
これは @sgk-000   のタスクの結果次第です

2022-05-16 07:47 UTC, yabuta commented on launch/lidartag_master.launch.xml
> +      <param name="min_rkhs_score" value="3.0" /> <!--default is 12.0 -->
なるほど。ではこのままにしましょうか

2022-05-16 07:49 UTC, knzo25 commented on launch/lidartag_master.launch.xml
> +      <param name="min_rkhs_score" value="3.0" /> <!--default is 12.0 -->
とりあえずそうしたほうがいいと思います

2022-05-16 07:56 UTC, knzo25 commented on src/utils.cpp
> +  /** Eigen Version -> Replaced by OpenCV since sgk-000 reported numerical unstability (unconfirmed)
これはSVDのimplementationの問題です。
作家はEigenを使いましたが @sgk-000 は使ってみたらnumerical errorを経験してCVに変更しました。

逆に、EigenのimplementationはCVよりコスパがいいと思いますので簡単に変更できるようにしておきたいと思います

2022-05-16 07:57 UTC, knzo25 commented on include/lidartag/lidartag.hpp
> +    int np_ring; // Unused
実はもとのlidartagの使われていないコードは山ほどありますが触りたくないと思います。
np_ring を削除しました。

2022-05-16 07:57 UTC, knzo25 commented on launch/lidartag_velodyne_vls128.launch.xml
> +    <arg name="linkage_ring_max_dist" value="2" /> <!-- This parameter be 1, but our lidar is missing one channel and this work as a hotfix -->
対応しました

2022-05-16 09:02 UTC, yabuta commented on src/utils.cpp
> +  /** Eigen Version -> Replaced by OpenCV since sgk-000 reported numerical unstability (unconfirmed)
了解です。それで良いと思います

2022-05-16 09:03 UTC, yabuta commented on include/lidartag/lidartag.hpp
> +    int np_ring; // Unused
なるほど。そう言うことなら今後は触らないようにしましょうか

2022-05-16 09:35 UTC, knzo25 commented on include/lidartag/lidartag.hpp
> +    int np_ring; // Unused
そうしましょう。”// Unused”は自分のメモでした

2022-05-19 04:50 UTC, aohsato approved these changes
LGTM

2022-05-25 01:10 UTC, aohsato approved these changes

2022-06-01 08:39 UTC, merged